name: Deploy Voll med

on:
  push:
    branches: ["main"]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configura JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Configura Docker Compose
      run: |
        curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Roda Docker Compose
      run: docker-compose up -d

    - name: Deploy para EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        USER: ubuntu
        HOST: 18.118.152.127
      run: |
        echo "$PRIVATE_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem

        docker save -o vollmed-api.tar vollmed-api-java_api

        scp -o StrickHostKeyCheck=no -i deploy_key.pem vollmed-api.tar $USER@$HOST:/home/ubuntu/
        scp -o StrickHostKeyCheck=no -i deploy_key.pem init.sql $USER@$HOST:/home/ubuntu/
        scp -o StrickHostKeyCheck=no -i deploy_key.pem docker-compose-prod.yaml $USER@$HOST:/home/ubuntu/
        scp -o StrickHostKeyCheck=no -i deploy_key.pem script-deploy.sh $USER@$HOST:/home/ubuntu/

        ssh -i deploy_key.pem $USER@$HOST "chmod +x script-deploy.sh && ./script-deploy.sh"
